name: Deployment

on:
  push:
    branches: master
jobs:
  
  
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        if: github.ref == 'refs/heads/master'
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{secrets.HOSTNAME}} '
            cd /var/www/html/chatbot &&
            sudo git pull origin master &&
            cd .. &&
            sudo mv chatbot/* /var/www/html &&
            python3 chatbot.py &&
            nohup gunicorn -w 1 -b 0.0.0.0:5001 chatbot:app > /dev/null 2>&1 &'
